services:
  request:
    class: Symfony\Component\HttpFoundation\Request
          
  catms.twig.twig_text_helpers:
      class: CatMS\AdminBundle\Twig\TwigTextHelpers
      tags:
          - { name: twig.extension }
          
  catms.twig.twig_catms_getters:
      class: CatMS\AdminBundle\Twig\TwigCatMSGetters
      arguments: ['@doctrine.orm.entity_manager'] 
      tags:
          - { name: twig.extension }   
          
  catms.twig.twig_catms_extension:
      class: CatMS\AdminBundle\Twig\TwigCatMSExtension
      arguments: ['@request', '@doctrine.orm.entity_manager'] 
      tags:
          - { name: twig.extension }          
