image-group:
    path:      /list/{page}
    defaults:  { _controller: CatMSAdminBundle:ImageGroup:index, page: 1 }
    requirements:
        page:  \d+
    methods:  [GET]

image-group-create:
    path:      /creation
    defaults:  { _controller: CatMSAdminBundle:ImageGroup:create }
    methods:  [POST] 
 
image-group-new:
    path:      /new
    defaults:  { _controller: CatMSAdminBundle:ImageGroup:new }
    methods:  [GET] 

image-group-show:
    path:      /{id}
    defaults:  { _controller: CatMSAdminBundle:ImageGroup:show }
    methods:  [GET] 

image-group-edit:
    path:   /edit/{id}/{group}
    defaults: {  _controller: CatMSAdminBundle:ImageGroup:edit, id: null, group: null }
    requirements:
        id:  \d+
    methods:  [GET] 

image-group-update:
    path:     /{id}
    defaults: {  _controller: CatMSAdminBundle:ImageGroup:update }
    requirements:
        id:  \d+
    methods:  [PUT] 

image-group-delete:
    path:     /{id}
    defaults: {  _controller: CatMSAdminBundle:ImageGroup:delete }
    requirements:
        id:  \d+
    methods:  [DELETE]   
    