default:
    paths:
        features: features
        bootstrap: %behat.paths.features%/bootstrap
        
    formatter:
        name:                       pretty
        parameters:
            decorated:              true
            verbose:                false
            time:                   true
            language:               en
            output_path:            null
            multiline_arguments:    true
            
            