cat_ms_admin:
    resource: "@CatMSAdminBundle/Controller/"
    type:     annotation
    prefix:   /
    
cat_ms_admin_media_library:
    resource: "@CatMSAdminBundle/Resources/config/media-library/routing.yml"
    prefix:   /admin/media-library

catms_auth_user:
    resource: "@CatMSAuthBundle/Resources/config/user/routing.yml"
    prefix:   /admin/user
    
catms_auth_security:
    resource: "@CatMSAuthBundle/Resources/config/security/routing.yml"
    prefix:   /auth
