content-group:
    path:      /list/{page}
    defaults:  { _controller: CatMSAdminBundle:ContentGroup:index, page: 1 }
    requirements:
        page:  \d+
    methods:  [GET]

content-group-create:
    path:      /creation
    defaults:  { _controller: CatMSAdminBundle:ContentGroup:create }
    methods:  [POST]
 
content-group-new:
    path:      /new
    defaults:  { _controller: CatMSAdminBundle:ContentGroup:new }
    methods:  [GET] 
    
content-group-show:
    path:      /{id}
    defaults:  { _controller: CatMSAdminBundle:ContentGroup:show }
    requirements:
        id:  \d+
    methods:  [GET] 

content-group-edit:
    path:   /{id}/edit
    defaults: {  _controller: CatMSAdminBundle:ContentGroup:edit }
    requirements:
        id:  \d+
    methods:  [GET] 
    
content-group-update:
    path:     /{id}
    defaults: {  _controller: CatMSAdminBundle:ContentGroup:update }
    requirements:
        id:  \d+
    methods:  [PUT] 
    
content-group-delete:
    path:     /{id}
    defaults: {  _controller: CatMSAdminBundle:ContentGroup:delete }
    requirements:
        id:  \d+
    methods:  [DELETE]